//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace file_cabinet.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class file_cabinetEntities1 : DbContext
    {
        private static file_cabinetEntities1 _context;
        public file_cabinetEntities1()
            : base("name=file_cabinetEntities1")
        {
        }
        public static file_cabinetEntities1 GetContext()
        {
            if (_context == null)
            {
                _context = new file_cabinetEntities1();
            }return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserAct> UserAct { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
